eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: school_service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: student_service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
